


image img1_sara_evening_pad_lose = MaxScale2("images/secret_gallery/Scenes/1.png")
image img2_sara_evening_pad_win = MaxScale2("images/secret_gallery/Scenes/2.png")
image img3_sara_night_visit_v1 = MaxScale2("images/secret_gallery/Scenes/3.png")
image img4_sara_botlle_game_v1 = MaxScale2("images/secret_gallery/Scenes/4.png")
image img5_celia_toilet_kiss_v1 = MaxScale2("images/secret_gallery/Scenes/5.png")
image img6_celia_toilet_fuck_v1 = MaxScale2("images/secret_gallery/Scenes/6.png")
image img7_celia_vibrator_classroom_v1 = MaxScale2("images/secret_gallery/Scenes/7.png")
image img8_caroline_ass_cosplay_v1 = MaxScale2("images/secret_gallery/Scenes/8.png")
image img9_violet_blowjob_v1 = MaxScale2("images/secret_gallery/Scenes/9.png")
image img10_caroline_visit_bjfjhj_v1 = MaxScale2("images/secret_gallery/Scenes/10.png")
image img11_mom_car_v1 = MaxScale2("images/secret_gallery/Scenes/11.png")
image img12_mom_work_hj_v1 = MaxScale2("images/secret_gallery/Scenes/12.png")
image img13_ml_room_fj_v1 = MaxScale2("images/secret_gallery/Scenes/13.png")

image img14_MLR2_ES3_rep = MaxScale2("images/secret_gallery/Scenes/14.png")
image img15_MLR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/15.png")
image img16_MLR2_weekend_rep = MaxScale2("images/secret_gallery/Scenes/16.png")
image img17_CR2_AS1_rep = MaxScale2("images/secret_gallery/Scenes/17.png")
image img18_CR2_AS2_rep = MaxScale2("images/secret_gallery/Scenes/18.png")
image img19_CR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/19.png")
image img20_Z_ES2_rep = MaxScale2("images/secret_gallery/Scenes/20.png")
image img21_Z_ES3_rep = MaxScale2("images/secret_gallery/Scenes/21.png")
image img22_Z_ES4_rep = MaxScale2("images/secret_gallery/Scenes/22.png")
image img23_SR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/23.png")
image img24_SR2_ES1_rep = MaxScale2("images/secret_gallery/Scenes/24.png")
image img25_SR2_NS3_rep = MaxScale2("images/secret_gallery/Scenes/25.png")
image img26_SR2_NS4_rep = MaxScale2("images/secret_gallery/Scenes/26.png")

image img27_CR3_week_rep = MaxScale2("images/secret_gallery/Scenes/27.png")
image img28_CR3_week2_rep = MaxScale2("images/secret_gallery/Scenes/28.png")
image img29_CR3_AS8_rep = MaxScale2("images/secret_gallery/Scenes/29.png")
image img30_CR3_AS9_rep = MaxScale2("images/secret_gallery/Scenes/30.png")
image img31_CR3_NS2_rep = MaxScale2("images/secret_gallery/Scenes/31.png")
image img32_CR3_NS3_rep = MaxScale2("images/secret_gallery/Scenes/32.png")
image img33_CR3_NS5_rep = MaxScale2("images/secret_gallery/Scenes/33.png")
image img34_LiR1_NS1_rep = MaxScale2("images/secret_gallery/Scenes/34.png")
image img35_LiR1_NS2_rep = MaxScale2("images/secret_gallery/Scenes/35.png")
image img36_LiR1_MS6_rep = MaxScale2("images/secret_gallery/Scenes/36.png")
image img37_LiR1_NS4_rep = MaxScale2("images/secret_gallery/Scenes/37.png")
image img38_LiR1_MS9_rep = MaxScale2("images/secret_gallery/Scenes/38.png")
image img39_LiR1_NS5_rep = MaxScale2("images/secret_gallery/Scenes/39.png")

image img40_MLR3_B_event_rep = MaxScale2("images/secret_gallery/Scenes/40.png")
image img41_MLR3_b_house_shower_rep = MaxScale2("images/secret_gallery/Scenes/41.png")
image img42_MLR3_AS3_rep = MaxScale2("images/secret_gallery/Scenes/42.png")
image img43_MLR3_NS1_rep = MaxScale2("images/secret_gallery/Scenes/43.png")
image img44_MLR3_NS2_rep = MaxScale2("images/secret_gallery/Scenes/44.png")

image secret_gallery_background = "images/secret_gallery/Bonus/Black.jpg"
image lockedthumb = MinScale2("images/secret_gallery/Bonus/locked.png", maxthumbx2, maxthumby2)




image thumb1_idle_sara_evening_pad_lose = MinScale2("images/secret_gallery/Scenes/1.png", maxthumbx2, maxthumby2)
image thumb2_idle_sara_evening_pad_win = MinScale2("images/secret_gallery/Scenes/2.png", maxthumbx2, maxthumby2)
image thumb3_idle_sara_night_visit_v1 = MinScale2("images/secret_gallery/Scenes/3.png", maxthumbx2, maxthumby2)
image thumb4_idle_sara_botlle_game_v1 = MinScale2("images/secret_gallery/Scenes/4.png", maxthumbx2, maxthumby2)
image thumb5_idle_celia_toilet_kiss_v1 = MinScale2("images/secret_gallery/Scenes/5.png", maxthumbx2, maxthumby2)
image thumb6_idle_celia_toilet_fuck_v1 = MinScale2("images/secret_gallery/Scenes/6.png", maxthumbx2, maxthumby2)
image thumb7_idle_celia_vibrator_classroom_v1 = MinScale2("images/secret_gallery/Scenes/7.png", maxthumbx2, maxthumby2)
image thumb8_idle_caroline_ass_cosplay_v1 = MinScale2("images/secret_gallery/Scenes/8.png", maxthumbx2, maxthumby2)
image thumb9_idle_violet_blowjob_v1 = MinScale2("images/secret_gallery/Scenes/9.png", maxthumbx2, maxthumby2)
image thumb10_idle_caroline_visit_bjfjhj_v1 = MinScale2("images/secret_gallery/Scenes/10.png", maxthumbx2, maxthumby2)
image thumb11_idle_mom_car_v1 = MinScale2("images/secret_gallery/Scenes/11.png", maxthumbx2, maxthumby2)
image thumb12_idle_mom_work_hj_v1 = MinScale2("images/secret_gallery/Scenes/12.png", maxthumbx2, maxthumby2)
image thumb13_idle_ml_room_fj_v1 = MinScale2("images/secret_gallery/Scenes/13.png", maxthumbx2, maxthumby2)

image thumb14_idle_MLR2_ES3_rep = MaxScale2("images/secret_gallery/Scenes/14.png", maxthumbx2, maxthumby2)
image thumb15_idle_MLR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/15.png", maxthumbx2, maxthumby2)
image thumb16_idle_MLR2_weekend_rep = MaxScale2("images/secret_gallery/Scenes/16.png", maxthumbx2, maxthumby2)
image thumb17_idle_CR2_AS1_rep = MaxScale2("images/secret_gallery/Scenes/17.png", maxthumbx2, maxthumby2)
image thumb18_idle_CR2_AS2_rep = MaxScale2("images/secret_gallery/Scenes/18.png", maxthumbx2, maxthumby2)
image thumb19_idle_CR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/19.png", maxthumbx2, maxthumby2)
image thumb20_idle_Z_ES2_rep = MaxScale2("images/secret_gallery/Scenes/20.png", maxthumbx2, maxthumby2)
image thumb21_idle_Z_ES3_rep = MaxScale2("images/secret_gallery/Scenes/21.png", maxthumbx2, maxthumby2)
image thumb22_idle_Z_ES4_rep = MaxScale2("images/secret_gallery/Scenes/22.png", maxthumbx2, maxthumby2)
image thumb23_idle_SR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/23.png", maxthumbx2, maxthumby2)
image thumb24_idle_SR2_ES1_rep = MaxScale2("images/secret_gallery/Scenes/24.png", maxthumbx2, maxthumby2)
image thumb25_idle_SR2_NS3_rep = MaxScale2("images/secret_gallery/Scenes/25.png", maxthumbx2, maxthumby2)
image thumb26_idle_SR2_NS4_rep = MaxScale2("images/secret_gallery/Scenes/26.png", maxthumbx2, maxthumby2)

image thumb27_idle_CR3_week_rep = MaxScale2("images/secret_gallery/Scenes/27.png", maxthumbx2, maxthumby2)
image thumb28_idle_CR3_week2_rep = MaxScale2("images/secret_gallery/Scenes/28.png", maxthumbx2, maxthumby2)
image thumb29_idle_CR3_AS8_rep = MaxScale2("images/secret_gallery/Scenes/29.png", maxthumbx2, maxthumby2)
image thumb30_idle_CR3_AS9_rep = MaxScale2("images/secret_gallery/Scenes/30.png", maxthumbx2, maxthumby2)
image thumb31_idle_CR3_NS2_rep = MaxScale2("images/secret_gallery/Scenes/31.png", maxthumbx2, maxthumby2)
image thumb32_idle_CR3_NS3_rep = MaxScale2("images/secret_gallery/Scenes/32.png", maxthumbx2, maxthumby2)
image thumb33_idle_CR3_NS5_rep = MaxScale2("images/secret_gallery/Scenes/33.png", maxthumbx2, maxthumby2)
image thumb34_idle_LiR1_NS1_rep = MaxScale2("images/secret_gallery/Scenes/34.png", maxthumbx2, maxthumby2)
image thumb35_idle_LiR1_NS2_rep = MaxScale2("images/secret_gallery/Scenes/35.png", maxthumbx2, maxthumby2)
image thumb36_idle_LiR1_MS6_rep = MaxScale2("images/secret_gallery/Scenes/36.png", maxthumbx2, maxthumby2)
image thumb37_idle_LiR1_NS4_rep = MaxScale2("images/secret_gallery/Scenes/37.png", maxthumbx2, maxthumby2)
image thumb38_idle_LiR1_MS9_rep = MaxScale2("images/secret_gallery/Scenes/38.png", maxthumbx2, maxthumby2)
image thumb39_idle_LiR1_NS5_rep = MaxScale2("images/secret_gallery/Scenes/39.png", maxthumbx2, maxthumby2)

image thumb40_idle_MLR3_B_event_rep = MaxScale2("images/secret_gallery/Scenes/40.png", maxthumbx2, maxthumby2)
image thumb41_idle_MLR3_b_house_shower_rep = MaxScale2("images/secret_gallery/Scenes/41.png", maxthumbx2, maxthumby2)
image thumb42_idle_MLR3_AS3_rep = MaxScale2("images/secret_gallery/Scenes/42.png", maxthumbx2, maxthumby2)
image thumb43_idle_MLR3_NS1_rep = MaxScale2("images/secret_gallery/Scenes/43.png", maxthumbx2, maxthumby2)
image thumb44_idle_MLR3_NS2_rep = MaxScale2("images/secret_gallery/Scenes/44.png", maxthumbx2, maxthumby2)

image thumb1_hover_sara_evening_pad_lose = MinScale2("images/secret_gallery/Scenes/1a.png", maxthumbx2, maxthumby2)
image thumb2_hover_sara_evening_pad_win = MinScale2("images/secret_gallery/Scenes/2a.png", maxthumbx2, maxthumby2)
image thumb3_hover_sara_night_visit_v1 = MinScale2("images/secret_gallery/Scenes/3a.png", maxthumbx2, maxthumby2)
image thumb4_hover_sara_botlle_game_v1 = MinScale2("images/secret_gallery/Scenes/4a.png", maxthumbx2, maxthumby2)
image thumb5_hover_celia_toilet_kiss_v1 = MinScale2("images/secret_gallery/Scenes/5a.png", maxthumbx2, maxthumby2)
image thumb6_hover_celia_toilet_fuck_v1 = MinScale2("images/secret_gallery/Scenes/6a.png", maxthumbx2, maxthumby2)
image thumb7_hover_celia_vibrator_classroom_v1 = MinScale2("images/secret_gallery/Scenes/7a.png", maxthumbx2, maxthumby2)
image thumb8_hover_caroline_ass_cosplay_v1 = MinScale2("images/secret_gallery/Scenes/8a.png", maxthumbx2, maxthumby2)
image thumb9_hover_violet_blowjob_v1 = MinScale2("images/secret_gallery/Scenes/9a.png", maxthumbx2, maxthumby2)
image thumb10_hover_caroline_visit_bjfjhj_v1 = MinScale2("images/secret_gallery/Scenes/10a.png", maxthumbx2, maxthumby2)
image thumb11_hover_mom_car_v1 = MinScale2("images/secret_gallery/Scenes/11a.png", maxthumbx2, maxthumby2)
image thumb12_hover_mom_work_hj_v1 = MinScale2("images/secret_gallery/Scenes/12a.png", maxthumbx2, maxthumby2)
image thumb13_hover_ml_room_fj_v1 = MinScale2("images/secret_gallery/Scenes/13a.png", maxthumbx2, maxthumby2)

image thumb14_hover_MLR2_ES3_rep = MaxScale2("images/secret_gallery/Scenes/14a.png", maxthumbx2, maxthumby2)
image thumb15_hover_MLR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/15a.png", maxthumbx2, maxthumby2)
image thumb16_hover_MLR2_weekend_rep = MaxScale2("images/secret_gallery/Scenes/16a.png", maxthumbx2, maxthumby2)
image thumb17_hover_CR2_AS1_rep = MaxScale2("images/secret_gallery/Scenes/17a.png", maxthumbx2, maxthumby2)
image thumb18_hover_CR2_AS2_rep = MaxScale2("images/secret_gallery/Scenes/18a.png", maxthumbx2, maxthumby2)
image thumb19_hover_CR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/19a.png", maxthumbx2, maxthumby2)
image thumb20_hover_Z_ES2_rep = MaxScale2("images/secret_gallery/Scenes/20a.png", maxthumbx2, maxthumby2)
image thumb21_hover_Z_ES3_rep = MaxScale2("images/secret_gallery/Scenes/21a.png", maxthumbx2, maxthumby2)
image thumb22_hover_Z_ES4_rep = MaxScale2("images/secret_gallery/Scenes/22a.png", maxthumbx2, maxthumby2)
image thumb23_hover_SR2_NS2_rep = MaxScale2("images/secret_gallery/Scenes/23a.png", maxthumbx2, maxthumby2)
image thumb24_hover_SR2_ES1_rep = MaxScale2("images/secret_gallery/Scenes/24a.png", maxthumbx2, maxthumby2)
image thumb25_hover_SR2_NS3_rep = MaxScale2("images/secret_gallery/Scenes/25a.png", maxthumbx2, maxthumby2)
image thumb26_hover_SR2_NS4_rep = MaxScale2("images/secret_gallery/Scenes/26a.png", maxthumbx2, maxthumby2)
image thumb27_hover_CR3_week_rep = MaxScale2("images/secret_gallery/Scenes/27a.png", maxthumbx2, maxthumby2)
image thumb28_hover_CR3_week2_rep = MaxScale2("images/secret_gallery/Scenes/28a.png", maxthumbx2, maxthumby2)
image thumb29_hover_CR3_AS8_rep = MaxScale2("images/secret_gallery/Scenes/29a.png", maxthumbx2, maxthumby2)
image thumb30_hover_CR3_AS9_rep = MaxScale2("images/secret_gallery/Scenes/30a.png", maxthumbx2, maxthumby2)
image thumb31_hover_CR3_NS2_rep = MaxScale2("images/secret_gallery/Scenes/31a.png", maxthumbx2, maxthumby2)
image thumb32_hover_CR3_NS3_rep = MaxScale2("images/secret_gallery/Scenes/32a.png", maxthumbx2, maxthumby2)
image thumb33_hover_CR3_NS5_rep = MaxScale2("images/secret_gallery/Scenes/33a.png", maxthumbx2, maxthumby2)
image thumb34_hover_LiR1_NS1_rep = MaxScale2("images/secret_gallery/Scenes/34a.png", maxthumbx2, maxthumby2)
image thumb35_hover_LiR1_NS2_rep = MaxScale2("images/secret_gallery/Scenes/35a.png", maxthumbx2, maxthumby2)
image thumb36_hover_LiR1_MS6_rep = MaxScale2("images/secret_gallery/Scenes/36a.png", maxthumbx2, maxthumby2)
image thumb37_hover_LiR1_NS4_rep = MaxScale2("images/secret_gallery/Scenes/37a.png", maxthumbx2, maxthumby2)
image thumb38_hover_LiR1_MS9_rep = MaxScale2("images/secret_gallery/Scenes/38a.png", maxthumbx2, maxthumby2)
image thumb39_hover_LiR1_NS5_rep = MaxScale2("images/secret_gallery/Scenes/39a.png", maxthumbx2, maxthumby2)

image thumb40_hover_MLR3_B_event_rep = MaxScale2("images/secret_gallery/Scenes/40a.png", maxthumbx2, maxthumby2)
image thumb41_hover_MLR3_b_house_shower_rep = MaxScale2("images/secret_gallery/Scenes/41a.png", maxthumbx2, maxthumby2)
image thumb42_hover_MLR3_AS3_rep = MaxScale2("images/secret_gallery/Scenes/42a.png", maxthumbx2, maxthumby2)
image thumb43_hover_MLR3_NS1_rep = MaxScale2("images/secret_gallery/Scenes/43a.png", maxthumbx2, maxthumby2)
image thumb44_hover_MLR3_NS2_rep = MaxScale2("images/secret_gallery/Scenes/44a.png", maxthumbx2, maxthumby2)